/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ebooks.main;

import com.ebooks.Compoment.MyButton;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    ImageIcon MainA = new ImageIcon("..\\DuAn01_G3_ebooks\\src\\com\\ebooks\\Icon\\apps (2).png");
    ImageIcon MainB = new ImageIcon("..\\DuAn01_G3_ebooks\\src\\com\\ebooks\\Icon\\apps (1).png");
    ImageIcon ManageB = new ImageIcon("..\\DuAn01_G3_ebooks\\src\\com\\ebooks\\Icon\\business-time 1.png");
    ImageIcon ManageA = new ImageIcon("..\\DuAn01_G3_ebooks\\src\\com\\ebooks\\Icon\\business-time (4).png");
    ImageIcon StatisticalA = new ImageIcon("..\\DuAn01_G3_ebooks\\src\\com\\ebooks\\Icon\\chart-area (4).png");
    ImageIcon StatisticalB = new ImageIcon("..\\DuAn01_G3_ebooks\\src\\com\\ebooks\\Icon\\chart-area (2).png");
    ImageIcon ReadA = new ImageIcon("..\\DuAn01_G3_ebooks\\src\\com\\ebooks\\Icon\\book-alt (4).png");
    ImageIcon ReadB = new ImageIcon("..\\DuAn01_G3_ebooks\\src\\com\\ebooks\\Icon\\book-alt (3).png");
    ImageIcon ListenA = new ImageIcon("..\\DuAn01_G3_ebooks\\src\\com\\ebooks\\Icon\\headphones (4).png");
    ImageIcon ListenB = new ImageIcon("..\\DuAn01_G3_ebooks\\src\\com\\ebooks\\Icon\\headphones (3).png");

    public Main() {
        initComponents();
//        init();
        setBackground(new Color(0, 0, 0, 0));

    }

    public void SetColorPanel(JPanel panel, boolean bl) {
        if (bl) {
            panel.setBackground(new Color(145, 227, 168));
        } else {
            panel.setBackground(new Color(205, 239, 215));

        }
    }

    public void SetColorIconBtn(MyButton btn, boolean bl, ImageIcon iconA, ImageIcon iconB) {
        if (bl) {
            btn.setIcon(iconA);
            btn.setBackground(new Color(145, 227, 168));
            btn.setBoderColor(new Color(145, 227, 168));
        } else {
            btn.setIcon(iconB);
            btn.setBackground(new Color(205, 239, 215));
            btn.setBoderColor(new Color(205, 239, 215));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.ebooks.Compoment.PanelBorder();
        jButton1 = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        panelRadius1 = new com.ebooks.Compoment.PanelRadius();
        pnlMain = new com.ebooks.Compoment.PanelRadius();
        btnMain = new com.ebooks.Compoment.MyButton();
        pnlManage = new com.ebooks.Compoment.PanelRadius();
        btnManage = new com.ebooks.Compoment.MyButton();
        pnlStatistical = new com.ebooks.Compoment.PanelRadius();
        btnStatistical = new com.ebooks.Compoment.MyButton();
        pnlRead = new com.ebooks.Compoment.PanelRadius();
        btnRead = new com.ebooks.Compoment.MyButton();
        pnlListen = new com.ebooks.Compoment.PanelRadius();
        btnListen = new com.ebooks.Compoment.MyButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new com.ebooks.Compoment.Table();
        panelRadius3 = new com.ebooks.Compoment.PanelRadius();
        panelRadius2 = new com.ebooks.Compoment.PanelRadius();
        jLabel1 = new javax.swing.JLabel();
        searchText1 = new com.ebooks.Compoment.SearchText();
        imageAvatar1 = new com.ebooks.Compoment.ImageAvatar();
        panelRadius4 = new com.ebooks.Compoment.PanelRadius();
        myButton1 = new com.ebooks.Compoment.MyButton();
        panelRadius5 = new com.ebooks.Compoment.PanelRadius();
        myButton2 = new com.ebooks.Compoment.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelBorder1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds.png"))); // NOI18N
        panelBorder1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        panelRadius1.setBackground(new java.awt.Color(205, 239, 215));
        panelRadius1.setRadius(20);
        panelRadius1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMain.setBackground(new java.awt.Color(145, 227, 168));
        pnlMain.setRadius(15);
        pnlMain.setLayout(new java.awt.GridBagLayout());

        btnMain.setBackground(new java.awt.Color(145, 227, 168));
        btnMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/apps (2).png"))); // NOI18N
        btnMain.setBoderColor(new java.awt.Color(145, 227, 168));
        btnMain.setFocusable(false);
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });
        pnlMain.add(btnMain, new java.awt.GridBagConstraints());

        panelRadius1.add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, 60, 60));

        pnlManage.setBackground(new java.awt.Color(205, 239, 215));
        pnlManage.setRadius(15);
        pnlManage.setLayout(new java.awt.GridBagLayout());

        btnManage.setBackground(new java.awt.Color(205, 239, 215));
        btnManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/business-time 1.png"))); // NOI18N
        btnManage.setBoderColor(new java.awt.Color(205, 239, 215));
        btnManage.setColorOver(new java.awt.Color(205, 239, 215));
        btnManage.setFocusable(false);
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });
        pnlManage.add(btnManage, new java.awt.GridBagConstraints());

        panelRadius1.add(pnlManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 100, 60, 60));

        pnlStatistical.setBackground(new java.awt.Color(205, 239, 215));
        pnlStatistical.setRadius(15);
        pnlStatistical.setLayout(new java.awt.GridBagLayout());

        btnStatistical.setBackground(new java.awt.Color(205, 239, 215));
        btnStatistical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/chart-area (2).png"))); // NOI18N
        btnStatistical.setBoderColor(new java.awt.Color(205, 239, 215));
        btnStatistical.setFocusable(false);
        btnStatistical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticalActionPerformed(evt);
            }
        });
        pnlStatistical.add(btnStatistical, new java.awt.GridBagConstraints());

        panelRadius1.add(pnlStatistical, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 180, 60, 60));

        pnlRead.setBackground(new java.awt.Color(205, 239, 215));
        pnlRead.setRadius(15);
        pnlRead.setLayout(new java.awt.GridBagLayout());

        btnRead.setBackground(new java.awt.Color(205, 239, 215));
        btnRead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/book-alt (3).png"))); // NOI18N
        btnRead.setBoderColor(new java.awt.Color(205, 239, 215));
        btnRead.setFocusable(false);
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });
        pnlRead.add(btnRead, new java.awt.GridBagConstraints());

        panelRadius1.add(pnlRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 260, 60, 60));

        pnlListen.setBackground(new java.awt.Color(205, 239, 215));
        pnlListen.setRadius(15);
        pnlListen.setLayout(new java.awt.GridBagLayout());

        btnListen.setBackground(new java.awt.Color(205, 239, 215));
        btnListen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/headphones (3).png"))); // NOI18N
        btnListen.setBoderColor(new java.awt.Color(205, 239, 215));
        btnListen.setFocusable(false);
        btnListen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListenActionPerformed(evt);
            }
        });
        pnlListen.add(btnListen, new java.awt.GridBagConstraints());

        panelRadius1.add(pnlListen, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 340, 60, 60));

        panelBorder1.add(panelRadius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, 450));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 710, 520));

        panelRadius3.setBackground(new java.awt.Color(231, 249, 234));
        panelRadius3.setRadius(20);

        javax.swing.GroupLayout panelRadius3Layout = new javax.swing.GroupLayout(panelRadius3);
        panelRadius3.setLayout(panelRadius3Layout);
        panelRadius3Layout.setHorizontalGroup(
            panelRadius3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panelRadius3Layout.setVerticalGroup(
            panelRadius3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jPanel1.add(panelRadius3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 300, 520));

        panelBorder1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 1070, 550));

        panelRadius2.setBackground(new java.awt.Color(205, 239, 215));
        panelRadius2.setRadius(20);
        panelRadius2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/search (1).png"))); // NOI18N
        panelRadius2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        searchText1.setBackground(new java.awt.Color(205, 239, 215));
        searchText1.setBorder(null);
        searchText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchText1ActionPerformed(evt);
            }
        });
        panelRadius2.add(searchText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 450, 40));

        panelBorder1.add(panelRadius2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 520, 60));

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/41b92ec3eab97e4c24b3f6e8fe75ddec.png"))); // NOI18N
        panelBorder1.add(imageAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 25, 70, 70));

        panelRadius4.setBackground(new java.awt.Color(205, 239, 215));
        panelRadius4.setRadius(10);
        panelRadius4.setLayout(new java.awt.GridBagLayout());

        myButton1.setBackground(new java.awt.Color(205, 239, 215));
        myButton1.setBorder(null);
        myButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/settings (1).png"))); // NOI18N
        myButton1.setBoderColor(new java.awt.Color(205, 239, 215));
        panelRadius4.add(myButton1, new java.awt.GridBagConstraints());

        panelBorder1.add(panelRadius4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 40, 40, 40));

        panelRadius5.setBackground(new java.awt.Color(205, 239, 215));
        panelRadius5.setRadius(10);
        panelRadius5.setLayout(new java.awt.GridBagLayout());

        myButton2.setBackground(new java.awt.Color(205, 239, 215));
        myButton2.setBorder(null);
        myButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/bell (1).png"))); // NOI18N
        myButton2.setBoderColor(new java.awt.Color(205, 239, 215));
        panelRadius5.add(myButton2, new java.awt.GridBagConstraints());

        panelBorder1.add(panelRadius5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 1230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        //SetColorPanel
        SetColorPanel(pnlMain, true);
        SetColorPanel(pnlManage, false);
        SetColorPanel(pnlStatistical, false);
        SetColorPanel(pnlRead, false);
        SetColorPanel(pnlListen, false);
        //SetColorBtn
        SetColorIconBtn(btnMain, true, MainA, MainB);
        SetColorIconBtn(btnManage, false, ManageA, ManageB);
        SetColorIconBtn(btnStatistical, false, StatisticalA, StatisticalB);
        SetColorIconBtn(btnRead, false, ReadA, ReadB);
        SetColorIconBtn(btnListen, false, ListenA, ListenB);

    }//GEN-LAST:event_btnMainActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        SetColorPanel(pnlMain, false);
        SetColorPanel(pnlManage, true);
        SetColorPanel(pnlStatistical, false);
        SetColorPanel(pnlRead, false);
        SetColorPanel(pnlListen, false);
         //SetColorBtn
        SetColorIconBtn(btnMain, false, MainA, MainB);
        SetColorIconBtn(btnManage, true, ManageA, ManageB);
        SetColorIconBtn(btnStatistical, false, StatisticalA, StatisticalB);
        SetColorIconBtn(btnRead, false, ReadA, ReadB);
        SetColorIconBtn(btnListen, false, ListenA, ListenB);
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnStatisticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticalActionPerformed
        SetColorPanel(pnlMain, false);
        SetColorPanel(pnlManage, false);
        SetColorPanel(pnlStatistical, true);
        SetColorPanel(pnlRead, false);
        SetColorPanel(pnlListen, false);
         //SetColorBtn
        SetColorIconBtn(btnMain, false, MainA, MainB);
        SetColorIconBtn(btnManage, false, ManageA, ManageB);
        SetColorIconBtn(btnStatistical, true, StatisticalA, StatisticalB);
        SetColorIconBtn(btnRead, false, ReadA, ReadB);
        SetColorIconBtn(btnListen, false, ListenA, ListenB);
    }//GEN-LAST:event_btnStatisticalActionPerformed

    private void btnListenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListenActionPerformed
        SetColorPanel(pnlMain, false);
        SetColorPanel(pnlManage, false);
        SetColorPanel(pnlStatistical, false);
        SetColorPanel(pnlRead, false);
        SetColorPanel(pnlListen, true);
         //SetColorBtn
        SetColorIconBtn(btnMain, false, MainA, MainB);
        SetColorIconBtn(btnManage, false, ManageA, ManageB);
        SetColorIconBtn(btnStatistical, false, StatisticalA, StatisticalB);
        SetColorIconBtn(btnRead, false, ReadA, ReadB);
        SetColorIconBtn(btnListen, true, ListenA, ListenB);
    }//GEN-LAST:event_btnListenActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        SetColorPanel(pnlMain, false);
        SetColorPanel(pnlManage, false);
        SetColorPanel(pnlStatistical, false);
        SetColorPanel(pnlRead, true);
        SetColorPanel(pnlListen, false);
        //SetColorBtn
        SetColorIconBtn(btnMain, false, MainA, MainB);
        SetColorIconBtn(btnManage, false, ManageA, ManageB);
        SetColorIconBtn(btnStatistical, false, StatisticalA, StatisticalB);
        SetColorIconBtn(btnRead, true, ReadA, ReadB);
        SetColorIconBtn(btnListen, false, ListenA, ListenB);
        
    }//GEN-LAST:event_btnReadActionPerformed

    private void searchText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchText1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ebooks.Compoment.MyButton btnListen;
    private com.ebooks.Compoment.MyButton btnMain;
    private com.ebooks.Compoment.MyButton btnManage;
    private com.ebooks.Compoment.MyButton btnRead;
    private com.ebooks.Compoment.MyButton btnStatistical;
    private com.ebooks.Compoment.ImageAvatar imageAvatar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private com.ebooks.Compoment.MyButton myButton1;
    private com.ebooks.Compoment.MyButton myButton2;
    private com.ebooks.Compoment.PanelBorder panelBorder1;
    private com.ebooks.Compoment.PanelRadius panelRadius1;
    private com.ebooks.Compoment.PanelRadius panelRadius2;
    private com.ebooks.Compoment.PanelRadius panelRadius3;
    private com.ebooks.Compoment.PanelRadius panelRadius4;
    private com.ebooks.Compoment.PanelRadius panelRadius5;
    private com.ebooks.Compoment.PanelRadius pnlListen;
    private com.ebooks.Compoment.PanelRadius pnlMain;
    private com.ebooks.Compoment.PanelRadius pnlManage;
    private com.ebooks.Compoment.PanelRadius pnlRead;
    private com.ebooks.Compoment.PanelRadius pnlStatistical;
    private com.ebooks.Compoment.SearchText searchText1;
    private com.ebooks.Compoment.Table table1;
    // End of variables declaration//GEN-END:variables
    public void init() {
        new StartUpDiaLog(this, true).setVisible(true);
        new LogInDiaLog(this, true).setVisible(true);

    }

}
