/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ebooks.main;

import com.ebooks.dao.NguoiDungDAO;
import com.ebooks.helper.DialogHelper;
import com.ebooks.helper.ShareHelper;
import com.ebooks.model.NguoiDung;
import com.sun.security.auth.NTSid;
import java.awt.Color;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thinh
 */
public class PersonDiaLog extends javax.swing.JDialog {

    File file;
    private NguoiDungDAO daoND = new NguoiDungDAO();

    public PersonDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        init();
    }

    public PersonDiaLog(java.awt.Frame parent, boolean modal, NguoiDung nd) {
        super(parent, modal);
        initComponents();
        setForm(nd);
        setBackground(new Color(0, 0, 0, 0));
    }

//////////////////////////////////////
    void init() {
        if (Main.MaND != null) {
            initForm();
        }
    }

    void insert() {
        NguoiDung model = getModel();
        if (model == null) {
            return;
        }
        try {
            daoND.insert(model);
            LoadNguoiDung();
            this.fillTable(Main.listND);
            DialogHelper.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            System.out.println(e);
            DialogHelper.alert(this, "Thêm mới thất bại!");
        }
    }

    void update() {
        try {
            NguoiDung model = getModel();
            daoND.update(model);
            LoadNguoiDung();
            this.fillTable(Main.listND);
        } catch (Exception e) {
            System.out.println(e);
            DialogHelper.alert(this, "Cập nhật thất bại!");
        }
    }

    void LoadNguoiDung() {
        Main.listND = daoND.selectAll();
    }

    void fillTable(List<NguoiDung> list) {
        Main.tblTable.setRowCount(0);
        try {

            for (NguoiDung emp : list) {
                Object[] row = {
                    emp.getMaNguoiDung(),
                    emp.getHoTen(),
                    emp.isGioiTinh() == true ? "Nam" : "Nữ",
                    emp.getSoDienThoai(),
                    emp.getEmail(),
                    emp.getHinh()};
                Main.tblTable.addRow(row);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    NguoiDung getModel() {

        NguoiDung model = new NguoiDung();
        model.setMaNguoiDung(txtMaNguoiDung.getText());
        model.setHoTen(txtHoTen.getText());
        model.setGioiTinh(rdoNam.isSelected() == true ? true : false);
        model.setSoDienThoai(txtSoDienThoai.getText());
        model.setEmail(txtEmail.getText());
        model.setHinh(file.toString());
        return model;
    }

    void selectImage() {
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {

            file = fileChooser.getSelectedFile();

            if (ShareHelper.saveLogo(file)) {
                // Hiển thị hình lên form
                imgHinh.setIcon(ShareHelper.readLogo(file.getName()));
                imgHinh.setToolTipText(file.getName());
                repaint();
            } else {
                DialogHelper.alert(this, "Vui lòng chọn file hình ảnh");
            }
        }
    }

    void initForm() {

        NguoiDung nguoiDung = daoND.findById(Main.MaND);

        txtMaNguoiDung.setText(nguoiDung.getMaNguoiDung());
        txtHoTen.setText(nguoiDung.getHoTen());
        if (nguoiDung.isGioiTinh()) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        txtSoDienThoai.setText(nguoiDung.getSoDienThoai());
        txtEmail.setText(nguoiDung.getEmail());

        ImageIcon icon = ShareHelper.readLogo(nguoiDung.getHinh());
        imgHinh.setIcon(icon);
        imgHinh.setToolTipText(nguoiDung.getHinh());

        repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelRadius2 = new com.ebooks.Compoment.PanelRadius();
        lblLogo1 = new javax.swing.JLabel();
        pnlExit1 = new com.ebooks.Compoment.PanelRound();
        lblExit1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        btnSave = new com.ebooks.Compoment.MyButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        imgHinh = new javax.swing.JLabel();
        txtMaNguoiDung = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnLuu = new com.ebooks.Compoment.MyButton();
        myButton106 = new com.ebooks.Compoment.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRadius2.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius2.setRadius(25);
        panelRadius2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelRadius2MouseMoved(evt);
            }
        });
        panelRadius2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds.png"))); // NOI18N
        panelRadius2.add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        pnlExit1.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit1.setRoundBottomLeft(25);
        pnlExit1.setRoundTopRight(25);
        pnlExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExit1MousePressed(evt);
            }
        });
        pnlExit1.setLayout(new java.awt.GridBagLayout());

        lblExit1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit1.setForeground(new java.awt.Color(255, 255, 255));
        lblExit1.setText("X");
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
        });
        pnlExit1.add(lblExit1, new java.awt.GridBagConstraints());

        panelRadius2.add(pnlExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 50));

        jLabel18.setFont(new java.awt.Font("Inter ExtraBold", 0, 26)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(55, 149, 76));
        jLabel18.setText("người dùng");
        panelRadius2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 150, -1));
        jLabel18.getAccessibleContext().setAccessibleName("Hãy điền các thông tin");

        txtSoDienThoai.setBackground(new java.awt.Color(222, 247, 227));
        panelRadius2.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 220, 40));

        jLabel4.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel4.setText("Số Điện Thoại");
        panelRadius2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        txtHoTen.setBackground(new java.awt.Color(222, 247, 227));
        panelRadius2.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 210, 40));

        jLabel6.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel6.setText("Mô Tả");
        panelRadius2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel2.setText("Giới Tính");
        panelRadius2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        txtEmail.setBackground(new java.awt.Color(222, 247, 227));
        panelRadius2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 210, 40));

        jLabel3.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel3.setText("Địa Chỉ Email");
        panelRadius2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");
        rdoNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNamActionPerformed(evt);
            }
        });
        panelRadius2.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");
        panelRadius2.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        btnSave.setBackground(new java.awt.Color(87, 190, 110));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Lưu Thông Tin");
        btnSave.setBoderColor(new java.awt.Color(87, 190, 110));
        btnSave.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        btnSave.setRadius(10);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panelRadius2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 270, 50));

        jLabel19.setFont(new java.awt.Font("Inter ExtraBold", 0, 26)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(55, 149, 76));
        jLabel19.setText("Hãy điền các thông tin");
        panelRadius2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 290, -1));

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane1.setViewportView(txtMoTa);

        panelRadius2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 670, 60));

        jLabel7.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel7.setText("Họ Tên Người Dùng");
        panelRadius2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jLabel32.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 24)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("N E R D S");
        panelRadius2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 50));

        jLabel33.setFont(new java.awt.Font("Adobe Myungjo Std M", 2, 10)); // NOI18N
        jLabel33.setText("Learning is the eye of the mind");
        panelRadius2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 160, -1));

        imgHinh.setBackground(new java.awt.Color(255, 255, 255));
        imgHinh.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        imgHinh.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        imgHinh.setOpaque(true);
        imgHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgHinhMouseClicked(evt);
            }
        });
        panelRadius2.add(imgHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, 170));

        txtMaNguoiDung.setBackground(new java.awt.Color(222, 247, 227));
        panelRadius2.add(txtMaNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 210, 40));

        jLabel9.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel9.setText("Mã người dùng");
        panelRadius2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        btnLuu.setBackground(new java.awt.Color(87, 190, 110));
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Cập nhật thông tin");
        btnLuu.setBoderColor(new java.awt.Color(87, 190, 110));
        btnLuu.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        btnLuu.setRadius(10);
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        panelRadius2.add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 230, 50));

        myButton106.setBackground(new java.awt.Color(87, 190, 110));
        myButton106.setForeground(new java.awt.Color(255, 255, 255));
        myButton106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Icon/refresh (1).png"))); // NOI18N
        myButton106.setText("Làm mới");
        myButton106.setBoderColor(new java.awt.Color(87, 190, 110));
        myButton106.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N
        myButton106.setRadius(10);
        myButton106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton106ActionPerformed(evt);
            }
        });
        panelRadius2.add(myButton106, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 140, 50));

        getContentPane().add(panelRadius2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblExit1MouseClicked

    private void pnlExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_pnlExit1MouseClicked

    private void pnlExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseEntered

    private void pnlExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseExited

    private void pnlExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_pnlExit1MousePressed

    private void rdoNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNamActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        insert();
        LoadNguoiDung();
        AppStatus.mainApp.fillTableNguoiDung(Main.listND);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void panelRadius2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRadius2MouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_panelRadius2MouseMoved

    private void imgHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgHinhMouseClicked
        // TODO add your handling code here:
        selectImage();
    }//GEN-LAST:event_imgHinhMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void myButton106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton106ActionPerformed
        // TODO add your handling code here:
        txtMaNguoiDung.setText("");
        txtHoTen.setText("");
        txtMoTa.setText("");
        txtSoDienThoai.setText("");
        txtEmail.setText("");
        txtMoTa.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_myButton106ActionPerformed

    public void setForm(NguoiDung nd) {
        txtHoTen.setText(nd.getHoTen());
        txtSoDienThoai.setText(nd.getSoDienThoai());
        if (nd.isGioiTinh()) {
            rdoNam.setEnabled(true);
        } else {
            rdoNam.setEnabled(false);
        }
    }

    /*tbdSetting args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PersonDiaLog dialog = new PersonDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ebooks.Compoment.MyButton btnLuu;
    private com.ebooks.Compoment.MyButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imgHinh;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblLogo1;
    private com.ebooks.Compoment.MyButton myButton106;
    private com.ebooks.Compoment.PanelRadius panelRadius2;
    private com.ebooks.Compoment.PanelRound pnlExit1;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNguoiDung;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtSoDienThoai;
    // End of variables declaration//GEN-END:variables
}
