/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ebooks.main;

import com.ebooks.dao.TaiKhoanDAO;
import com.ebooks.helper.DialogHelper;
import com.ebooks.helper.ShareHelper;
import com.ebooks.helper.UtilityHelper;
import com.ebooks.model.TaiKhoan;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 *
 * @author Thinh
 */
public class SettingDiaLog extends javax.swing.JDialog {

    boolean DangXuat = false;
    TaiKhoanDAO DAOTK = new TaiKhoanDAO();
    public  SettingDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DangXuat(parent);
        setBackground(new Color(0,0,0,0));
        initMoving(this, pnlMainDialog);
    }
    
    private int x;
    private int y;

    public void initMoving(JDialog DiaLog, JPanel panel) {
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                x = me.getX();
                y = me.getY();
            }

        });
        panel.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me) {
                DiaLog.setLocation(me.getXOnScreen() - x, me.getYOnScreen() - y);
            }
        });
    }
    
    public void DangXuat(Frame frame){
        if(DangXuat){
            frame.setVisible(false);
        }
    }
    
    public void DoiMatKhau(){
         if (UtilityHelper.checkNullText(lblTenDangNhap,txtTenDangNhap)) {
            String TenDangNhap = txtTenDangNhap.getText();
            if (UtilityHelper.checkPass(lblMatKhau,txtPass)) {
                String matKhau = new String(txtPass.getPassword());
                if (UtilityHelper.checkPass(lblMatKhauMoi,txtNewPass)) {
                    String matKhauMoi = new String(txtNewPass.getPassword());
                    if (UtilityHelper.checkPass(lblXacNhan,txtConfirm)) {
                        String XacNhanMK = new String(txtConfirm.getPassword());
                        if (!TenDangNhap.equalsIgnoreCase(ShareHelper.USER.getTenDangNhap())) {
                            DialogHelper.alert(this, "Sai Tên Đăng Nhập");
                            txtTenDangNhap.setText("");
                            txtTenDangNhap.requestFocus();
                            return;
                        } else if (!matKhau.equals(ShareHelper.USER.getMatKhau())) {
                            DialogHelper.alert(this, "Sai Mật Khẩu");
                            txtPass.setText("");
                            txtPass.requestFocus();
                            return;
                        } else if (!matKhauMoi.equals(XacNhanMK)) {
                            DialogHelper.alert(this, "Xác Nhận Không Đúng");
                            txtNewPass.setText("");
                            txtConfirm.setText("");
                            txtNewPass.requestFocus();
                            return;
                        } else {
                            ShareHelper.USER.setMatKhau(matKhauMoi);
                            DAOTK.update(ShareHelper.USER);
                            DialogHelper.alert(this, "Đổi Mật Khẩu Thành Công");
                            this.dispose();
                        }
                    }
                }

            }

        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainDialog = new com.ebooks.Compoment.PanelRadius();
        jLabel1 = new javax.swing.JLabel();
        tbdSetting = new com.ebooks.Compoment.MaterialTabbed();
        panelRadius2 = new com.ebooks.Compoment.PanelRadius();
        jLabel2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        panelRadius4 = new com.ebooks.Compoment.PanelRadius();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        lblMatKhau = new javax.swing.JLabel();
        lblMatKhauMoi = new javax.swing.JLabel();
        lblXacNhan = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JPasswordField();
        txtPass = new javax.swing.JPasswordField();
        txtNewPass = new javax.swing.JPasswordField();
        btnLuuTaiKhoan = new com.ebooks.Compoment.MyButton();
        panelRadius5 = new com.ebooks.Compoment.PanelRadius();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnDangXuat = new com.ebooks.Compoment.MyButton();
        panelRadius3 = new com.ebooks.Compoment.PanelRadius();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnXoaTaiKhoan = new com.ebooks.Compoment.MyButton();
        jLabel16 = new javax.swing.JLabel();
        pnlExit = new com.ebooks.Compoment.PanelRound();
        lblExit = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMainDialog.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainDialog.setRadius(25);
        pnlMainDialog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Inter", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cài Đặt ");
        pnlMainDialog.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 120, -1));

        tbdSetting.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tbdSetting.setFont(new java.awt.Font("Inter SemiBold", 0, 12)); // NOI18N

        panelRadius2.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel2.setText("Thông Tin Về Ứng Dụng ");
        panelRadius2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        panelRadius2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 700, 10));

        tbdSetting.addTab("Giới Thiệu", panelRadius2);

        panelRadius4.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRadius4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 700, 10));

        jLabel3.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel3.setText("Đổi Mật Khẩu Tài Khoản");
        panelRadius4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblTenDangNhap.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenDangNhap.setText("Tên Đăng Nhập");
        panelRadius4.add(lblTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtTenDangNhap.setBackground(new java.awt.Color(222, 247, 227));
        txtTenDangNhap.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        panelRadius4.add(txtTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, 40));

        lblMatKhau.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMatKhau.setText("Mật Khẩu");
        panelRadius4.add(lblMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        lblMatKhauMoi.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMatKhauMoi.setText("Mật Khẩu Mới ");
        panelRadius4.add(lblMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lblXacNhan.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblXacNhan.setText("Xác Nhận");
        panelRadius4.add(lblXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        txtConfirm.setBackground(new java.awt.Color(222, 247, 227));
        txtConfirm.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        panelRadius4.add(txtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 260, 40));

        txtPass.setBackground(new java.awt.Color(222, 247, 227));
        txtPass.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        panelRadius4.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 260, 40));

        txtNewPass.setBackground(new java.awt.Color(222, 247, 227));
        txtNewPass.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        txtNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPassActionPerformed(evt);
            }
        });
        panelRadius4.add(txtNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 260, 40));

        btnLuuTaiKhoan.setBackground(new java.awt.Color(87, 190, 110));
        btnLuuTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuTaiKhoan.setText("Lưu Tài Khoản");
        btnLuuTaiKhoan.setBoderColor(new java.awt.Color(87, 190, 110));
        btnLuuTaiKhoan.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        btnLuuTaiKhoan.setRadius(10);
        btnLuuTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuTaiKhoanActionPerformed(evt);
            }
        });
        panelRadius4.add(btnLuuTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 220, 40));

        tbdSetting.addTab("Đổi Mật Khẩu", panelRadius4);

        panelRadius5.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRadius5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 700, 10));

        jLabel4.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel4.setText("Đăng Xuất Tài Khoản");
        panelRadius5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Sau khi đăng xuất bạn sẽ phải rời khỏi giao diện chính của ứng dụng và chỉ vào giao");
        panelRadius5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 650, -1));

        jLabel11.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("giao diện chính lần nữa thì phải đăng nhập vào ứng dụng hoạt đăng ký một tài khoản");
        panelRadius5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 650, -1));

        jLabel12.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("khác để tiếp tục sữ dụng phần mềm của chúng tôi.");
        panelRadius5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        btnDangXuat.setBackground(new java.awt.Color(87, 190, 110));
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setText("Đăng Xuất Tài Khoản");
        btnDangXuat.setBoderColor(new java.awt.Color(87, 190, 110));
        btnDangXuat.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        btnDangXuat.setRadius(10);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        panelRadius5.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 40));

        tbdSetting.addTab("Đăng Xuất", panelRadius5);

        panelRadius3.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRadius3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 700, 10));

        jLabel5.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N
        jLabel5.setText("Xóa Tài Khoản");
        panelRadius3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Sau khi bạn xóa tài khoản bạn không thể đăng nhập vào ứng dụng bằng tài khoản ");
        panelRadius3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 660, -1));

        jLabel14.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("bị xóa và tài khoản sau khi xóa sẽ vĩnh viễn mất. Nếu bạn muốn sử dụng ứng dụng ");
        panelRadius3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 640, -1));

        jLabel15.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("dụng này.");
        panelRadius3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btnXoaTaiKhoan.setBackground(new java.awt.Color(253, 127, 127));
        btnXoaTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaTaiKhoan.setText("Xóa Tài Khoản");
        btnXoaTaiKhoan.setBoderColor(new java.awt.Color(253, 127, 127));
        btnXoaTaiKhoan.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        btnXoaTaiKhoan.setRadius(10);
        btnXoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTaiKhoanActionPerformed(evt);
            }
        });
        panelRadius3.add(btnXoaTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 220, 40));

        jLabel16.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("dụng tiếp tục thì phải đăng ký một tài khoản mới để có thể tiếp tục trãi nghiệm ứng");
        panelRadius3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        tbdSetting.addTab("Xóa Tài Khoản", panelRadius3);

        pnlMainDialog.add(tbdSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 830, 390));

        pnlExit.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit.setRoundBottomLeft(25);
        pnlExit.setRoundTopRight(25);
        pnlExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExitMouseExited(evt);
            }
        });
        pnlExit.setLayout(new java.awt.GridBagLayout());

        lblExit.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("X");
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        pnlExit.add(lblExit, new java.awt.GridBagConstraints());

        pnlMainDialog.add(pnlExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        pnlMainDialog.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(pnlMainDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPassActionPerformed

    private void btnXoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaTaiKhoanActionPerformed

    private void pnlExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_pnlExitMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void pnlExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseEntered
        pnlExit.setBackground(new Color(233,111,111));
    }//GEN-LAST:event_pnlExitMouseEntered

    private void pnlExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExitMouseExited
        pnlExit.setBackground(new Color(253,127,127));
    }//GEN-LAST:event_pnlExitMouseExited

    private void btnLuuTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuTaiKhoanActionPerformed
       DoiMatKhau();
    }//GEN-LAST:event_btnLuuTaiKhoanActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        DangXuat = true;
        
    }//GEN-LAST:event_btnDangXuatActionPerformed

    /*tbdSetting args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SettingDiaLog dialog = new SettingDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ebooks.Compoment.MyButton btnDangXuat;
    private com.ebooks.Compoment.MyButton btnLuuTaiKhoan;
    private com.ebooks.Compoment.MyButton btnXoaTaiKhoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblMatKhauMoi;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JLabel lblXacNhan;
    private com.ebooks.Compoment.PanelRadius panelRadius2;
    private com.ebooks.Compoment.PanelRadius panelRadius3;
    private com.ebooks.Compoment.PanelRadius panelRadius4;
    private com.ebooks.Compoment.PanelRadius panelRadius5;
    private com.ebooks.Compoment.PanelRound pnlExit;
    private com.ebooks.Compoment.PanelRadius pnlMainDialog;
    private com.ebooks.Compoment.MaterialTabbed tbdSetting;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
