/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ebooks.main;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Thinh
 */
public class TableRentCostDialog extends javax.swing.JDialog {

    /**
     * Creates new form TableRentCostDialog
     */
    public TableRentCostDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRadius1 = new com.ebooks.Compoment.PanelRadius();
        pnlExit1 = new com.ebooks.Compoment.PanelRound();
        lblExit1 = new javax.swing.JLabel();
        btnLuuThong = new com.ebooks.Compoment.MyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        lblMaSach = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        SprHour = new javax.swing.JSpinner();
        SprMin = new javax.swing.JSpinner();
        SprSec = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaSach1 = new javax.swing.JTextField();
        lblMaSach1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRadius1.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius1.setRadius(25);
        panelRadius1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlExit1.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit1.setRoundBottomLeft(25);
        pnlExit1.setRoundTopRight(25);
        pnlExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExit1MouseExited(evt);
            }
        });
        pnlExit1.setLayout(new java.awt.GridBagLayout());

        lblExit1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit1.setForeground(new java.awt.Color(255, 255, 255));
        lblExit1.setText("X");
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
        });
        pnlExit1.add(lblExit1, new java.awt.GridBagConstraints());

        panelRadius1.add(pnlExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 50, 50));

        btnLuuThong.setBackground(new java.awt.Color(87, 190, 110));
        btnLuuThong.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuThong.setText("Lưu Thông Tin");
        btnLuuThong.setBoderColor(new java.awt.Color(87, 190, 110));
        btnLuuThong.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        btnLuuThong.setRadius(10);
        btnLuuThong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuThongActionPerformed(evt);
            }
        });
        panelRadius1.add(btnLuuThong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 270, 50));

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        txtMoTa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMoTaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtMoTa);

        panelRadius1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 540, 80));

        jLabel19.setFont(new java.awt.Font("Inter ExtraBold", 0, 26)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(55, 149, 76));
        jLabel19.setText("Bảng Giá Thuê");
        panelRadius1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, -1));

        lblMaSach.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMaSach.setText("Mã Sách");
        panelRadius1.add(lblMaSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtDonGia.setBackground(new java.awt.Color(222, 247, 227));
        txtDonGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDonGiaKeyPressed(evt);
            }
        });
        panelRadius1.add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 240, 40));

        SprHour.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        panelRadius1.add(SprHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 60, 40));

        SprMin.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        panelRadius1.add(SprMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 60, 40));

        SprSec.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        panelRadius1.add(SprSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 60, 40));

        jLabel12.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Sec");
        panelRadius1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 60, 20));

        jLabel11.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Min");
        panelRadius1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 60, -1));

        jLabel9.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Hour");
        panelRadius1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 60, 20));

        jLabel10.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel10.setText("Thời lượng");
        panelRadius1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        txtMaSach1.setBackground(new java.awt.Color(222, 247, 227));
        txtMaSach1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaSach1KeyPressed(evt);
            }
        });
        panelRadius1.add(txtMaSach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 240, 40));

        lblMaSach1.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMaSach1.setText("Đơn Giá");
        panelRadius1.add(lblMaSach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel6.setText("Mô Tả");
        panelRadius1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        panelRadius1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(panelRadius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblExit1MouseClicked

    private void pnlExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_pnlExit1MouseClicked

    private void pnlExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseEntered

    private void pnlExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseExited

    private void btnLuuThongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuThongActionPerformed
       
    }//GEN-LAST:event_btnLuuThongActionPerformed

    private void txtMoTaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoTaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           
        }
    }//GEN-LAST:event_txtMoTaKeyPressed

    private void txtDonGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDonGiaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           
        }
    }//GEN-LAST:event_txtDonGiaKeyPressed

    private void txtMaSach1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaSach1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSach1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableRentCostDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableRentCostDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableRentCostDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableRentCostDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TableRentCostDialog dialog = new TableRentCostDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SprHour;
    private javax.swing.JSpinner SprMin;
    private javax.swing.JSpinner SprSec;
    private com.ebooks.Compoment.MyButton btnLuuThong;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblMaSach;
    private javax.swing.JLabel lblMaSach1;
    private com.ebooks.Compoment.PanelRadius panelRadius1;
    private com.ebooks.Compoment.PanelRound pnlExit1;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaSach1;
    private javax.swing.JTextArea txtMoTa;
    // End of variables declaration//GEN-END:variables
}
