package com.ebooks.main;

import com.ebooks.dao.BangGiaThueDAO;
import com.ebooks.dao.ThucUongDAO;
import com.ebooks.helper.DialogHelper;
import com.ebooks.helper.UtilityHelper;
import com.ebooks.model.BangGiaThue;
import com.ebooks.model.ThucUong;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JDialog;
import javax.swing.JPanel;
import java.sql.Time;
import java.util.ArrayList;
import java.util.List;

public class TableRentCostDialog extends javax.swing.JDialog {

    public TableRentCostDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        initMoving(this, panelRadius1);
    }
    
    public TableRentCostDialog(java.awt.Frame parent, boolean modal, BangGiaThue bangGiaThue) {
        super(parent, modal);
        initComponents();
        setForm(bangGiaThue);
        setBackground(new Color(0, 0, 0, 0));
        initMoving(this, panelRadius1);
        txtMaGiaThue.setEditable(false);
    }

    private int x;
    private int y;
    List<BangGiaThue> listGT = new ArrayList();

    public void initMoving(JDialog DiaLog, JPanel panel) {
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                x = me.getX();
                y = me.getY();
            }

        });
        panel.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me) {
                DiaLog.setLocation(me.getXOnScreen() - x, me.getYOnScreen() - y);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRadius1 = new com.ebooks.Compoment.PanelRadius();
        pnlExit1 = new com.ebooks.Compoment.PanelRound();
        lblExit1 = new javax.swing.JLabel();
        btnLuuThong = new com.ebooks.Compoment.MyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        lblMaGiaThue = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        SprHour = new javax.swing.JSpinner();
        SprMin = new javax.swing.JSpinner();
        SprSec = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaGiaThue = new javax.swing.JTextField();
        lblDonGia = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRadius1.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius1.setRadius(25);
        panelRadius1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlExit1.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit1.setRoundBottomLeft(25);
        pnlExit1.setRoundTopRight(25);
        pnlExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExit1MouseExited(evt);
            }
        });
        pnlExit1.setLayout(new java.awt.GridBagLayout());

        lblExit1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit1.setForeground(new java.awt.Color(255, 255, 255));
        lblExit1.setText("X");
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
        });
        pnlExit1.add(lblExit1, new java.awt.GridBagConstraints());

        panelRadius1.add(pnlExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 50, 50));

        btnLuuThong.setBackground(new java.awt.Color(87, 190, 110));
        btnLuuThong.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuThong.setText("Lưu Thông Tin");
        btnLuuThong.setBoderColor(new java.awt.Color(87, 190, 110));
        btnLuuThong.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        btnLuuThong.setRadius(10);
        btnLuuThong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuThongActionPerformed(evt);
            }
        });
        panelRadius1.add(btnLuuThong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 270, 50));

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        txtMoTa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMoTaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtMoTa);

        panelRadius1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 540, 80));

        jLabel19.setFont(new java.awt.Font("Inter ExtraBold", 0, 26)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(55, 149, 76));
        jLabel19.setText("Bảng Giá Thuê");
        panelRadius1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 210, -1));

        lblMaGiaThue.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMaGiaThue.setText("Mã Giá Thuê");
        panelRadius1.add(lblMaGiaThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtDonGia.setBackground(new java.awt.Color(222, 247, 227));
        txtDonGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDonGiaKeyPressed(evt);
            }
        });
        panelRadius1.add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 240, 40));

        SprHour.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        panelRadius1.add(SprHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 60, 40));

        SprMin.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        panelRadius1.add(SprMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 60, 40));

        SprSec.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        panelRadius1.add(SprSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 60, 40));

        jLabel12.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Sec");
        panelRadius1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 60, 20));

        jLabel11.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Min");
        panelRadius1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 60, -1));

        jLabel9.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Hour");
        panelRadius1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 60, 20));

        jLabel10.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel10.setText("Thời lượng");
        panelRadius1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        txtMaGiaThue.setBackground(new java.awt.Color(222, 247, 227));
        txtMaGiaThue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaGiaThueKeyPressed(evt);
            }
        });
        panelRadius1.add(txtMaGiaThue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 240, 40));

        lblDonGia.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblDonGia.setText("Đơn Giá");
        panelRadius1.add(lblDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        jLabel6.setText("Mô Tả");
        panelRadius1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        panelRadius1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(panelRadius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblExit1MouseClicked

    private void pnlExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_pnlExit1MouseClicked

    private void pnlExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseEntered

    private void pnlExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseExited

    private void btnLuuThongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuThongActionPerformed
        String maGiaThue = txtMaGiaThue.getText();
        int timThay = 0;
        BangGiaThueDAO DaoGT = new BangGiaThueDAO();
        listGT = DaoGT.selectAll();
        
        for (BangGiaThue x : listGT) {
            if (x.getMaGiaThue().contains(maGiaThue)) {
                timThay = 1;
            }
        }
        
        if(timThay == 0) {
            this.insert();
        } else{
            if (DialogHelper.confirm(this, "Chắc chắn cập nhật?")) {
                this.update();
            }
        }
        
    }//GEN-LAST:event_btnLuuThongActionPerformed

    private void txtMoTaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoTaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        }
    }//GEN-LAST:event_txtMoTaKeyPressed

    private void txtDonGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDonGiaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        }
    }//GEN-LAST:event_txtDonGiaKeyPressed

    private void txtMaGiaThueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaGiaThueKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGiaThueKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableRentCostDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableRentCostDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableRentCostDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableRentCostDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TableRentCostDialog dialog = new TableRentCostDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SprHour;
    private javax.swing.JSpinner SprMin;
    private javax.swing.JSpinner SprSec;
    private com.ebooks.Compoment.MyButton btnLuuThong;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblMaGiaThue;
    private com.ebooks.Compoment.PanelRadius panelRadius1;
    private com.ebooks.Compoment.PanelRound pnlExit1;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaGiaThue;
    private javax.swing.JTextArea txtMoTa;
    // End of variables declaration//GEN-END:variables
  
    public BangGiaThue getForm() {
        String thoiLuong = SprHour.getValue().toString() +":"+SprMin.getValue().toString() +":"+SprSec.getValue().toString();
        BangGiaThue gt = new BangGiaThue();
        gt.setMaGiaThue(txtMaGiaThue.getText());
        gt.setThoiLuong(Time.valueOf(thoiLuong));
        gt.setDonGiaThue(Double.parseDouble(txtDonGia.getText()));
        return gt;
    }
    
    public BangGiaThue getForm(BangGiaThue gt) {
        String thoiLuong = SprHour.getValue().toString() +":"+SprMin.getValue().toString() +":"+SprSec.getValue().toString();
//        BangGiaThue gt = new BangGiaThue();
        gt.setMaGiaThue(txtMaGiaThue.getText());
        gt.setThoiLuong(Time.valueOf(thoiLuong));
        gt.setDonGiaThue(Double.parseDouble(txtDonGia.getText()));
        
        return gt;
    }
    
    public void setForm(BangGiaThue giaThue) {
        txtMaGiaThue.setText(giaThue.getMaGiaThue());
        txtDonGia.setText(String.valueOf(giaThue.getDonGiaThue()));
        String[] gio = giaThue.getThoiLuong().toString().split("\\:");
        SprHour.setValue(Integer.parseInt(gio[0]));
        SprMin.setValue(Integer.parseInt(gio[1]));
        SprSec.setValue(Integer.parseInt(gio[2]));
    }
    
    BangGiaThueDAO DAOGiaThue = new BangGiaThueDAO();
    //them mơi
    public void insert() {
        if (UtilityHelper.checkNullText(lblMaGiaThue, txtMaGiaThue) && UtilityHelper.checkMa(lblMaGiaThue, txtMaGiaThue)) {
            if (UtilityHelper.checkNullText(lblDonGia, txtDonGia) && UtilityHelper.checkName(lblDonGia, txtDonGia)) {

                try {
                    BangGiaThue GT = getForm();
                    DAOGiaThue.insert(GT);
//                      this.fillTable();
                    DialogHelper.alert(this, "Thêm mới Thành công");
                } catch (Exception e) {
                    DialogHelper.alert(this, "Thêm Mới Thất Bại!");
                }

            }
        }
    }
    
    public void update() {
        if (UtilityHelper.checkNullText(lblMaGiaThue, txtMaGiaThue) && UtilityHelper.checkMa(lblMaGiaThue, txtMaGiaThue)) {
            if (UtilityHelper.checkNullText(lblDonGia, txtDonGia) && UtilityHelper.checkName(lblDonGia, txtDonGia)) {

                try {
                        String maGiaThue = txtMaGiaThue.getText();
                                
                        BangGiaThue GT = DAOGiaThue.findById(maGiaThue);
                        DAOGiaThue.update(getForm(GT));
//                                this.fillTable();
                        DialogHelper.alert(this, "Cập nhật Thành công");
                    } catch (Exception e) {
                        DialogHelper.alert(this, "Cập nhật Thất Bại!");
                    }

            }
        }
    }
}
