/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ebooks.main;

import com.ebooks.dao.TheLoaiDAO;
import com.ebooks.helper.DialogHelper;
import com.ebooks.helper.ShareHelper;
import com.ebooks.helper.UtilityHelper;
import com.ebooks.model.LoaiSS;
import com.ebooks.model.TheLoai;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 *
 * @author Thinh
 */
public class TypeBooksDiaLog extends javax.swing.JDialog {

    private List<TheLoai> listTL = new ArrayList<>();
    private TheLoaiDAO DAOTL = new TheLoaiDAO();

    public TypeBooksDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        initMoving(this, pnlMainDialog);
    }

    public TypeBooksDiaLog(java.awt.Frame parent, boolean modal, TheLoai tloai) {
        super(parent, modal);
        initComponents();
        setForm(tloai);
        setBackground(new Color(0, 0, 0, 0));
        initMoving(this, pnlMainDialog);
    }

    private int x;
    private int y;

    public void initMoving(JDialog DiaLog, JPanel panel) {
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                x = me.getX();
                y = me.getY();
            }

        });
        panel.addMouseMotionListener(new MouseMotionAdapter() {
            @Override
            public void mouseDragged(MouseEvent me) {
                DiaLog.setLocation(me.getXOnScreen() - x, me.getYOnScreen() - y);
            }
        });
    }

    public void setForm(TheLoai tloai) {
        txtMaTheLoai.setText(tloai.getMaTheLoai());
        txtTenTheLoai.setText(tloai.getTenTheLoai());
        txtMoTaTL.setText(tloai.getMoTaTheLoai());
    }

    TheLoai getForm() {
        TheLoai theLoai = new TheLoai();
        theLoai.setMaTheLoai(txtMaTheLoai.getText());
        theLoai.setTenTheLoai(txtTenTheLoai.getText());
        theLoai.setMoTaTheLoai(txtMoTaTL.getText());
        theLoai.setMaQuanTriVien(ShareHelper.BOSS.getMaQuanTriVien());
        return theLoai;
    }

    // CAC NUT BUTTON
    public void InsertTacGia() {
        if (UtilityHelper.checkNullText(lblMaTL, txtMaTheLoai)) {
            if (UtilityHelper.checkNullText(lblTenTL, txtTenTheLoai)) {
                TheLoai theLoai = getForm();
                DAOTL.insert(theLoai);

                try {
                    // this.fill
                    DialogHelper.alert(this, "Thêm mới Thành công");
                } catch (Exception e) {
                    DialogHelper.alert(this, "Lỗi thêm tác giả");
                    return;
                }
            }
        }
    }

    public void UpdateSach() {
        if (UtilityHelper.checkNullText(lblMaTL, txtMaTheLoai) ) {
            if (UtilityHelper.checkNullText(lblTenTL, txtTenTheLoai)) {
              //  TacGia tacGia = DAOTG.findById(maTacGia);
              TheLoai tenTL = getForm();
                System.out.println(tenTL);
                if (tenTL != null) {
                    try {
                        DAOTL.update(tenTL);
                        DialogHelper.alert(this, "Cập Nhật Thành Công");
                    } catch (Exception e) {
                        DialogHelper.alert(this, "Lỗi Cập Nhật");
                    }
                } else {
                    DialogHelper.alert(this, "Cập Nhật Thất Bại");
                }

            }
        }
    }
    
    
    public void LuuThongTin(){
        String maTL = txtMaTheLoai.getText();
        int timThay = 0;
//        ThucUongDAO DaoTU = new ThucUongDAO();
        listTL = DAOTL.selectAll();
        for (TheLoai x : listTL) {
            if (x.getMaTheLoai().contains(maTL)) {
                timThay = 1;
            }
        }
        if (timThay == 0) {
            this.InsertTacGia();
        } else {
            if (DialogHelper.confirm(this, "Chắc chắn cập nhật?")) {
                this.UpdateSach();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlMainDialog = new com.ebooks.Compoment.PanelRadius();
        pnlExit1 = new com.ebooks.Compoment.PanelRound();
        lblExit1 = new javax.swing.JLabel();
        txtMaTheLoai = new javax.swing.JTextField();
        lblMoTaTL = new javax.swing.JLabel();
        txtTenTheLoai = new javax.swing.JTextField();
        lblTenTL = new javax.swing.JLabel();
        btnLuuTL = new com.ebooks.Compoment.MyButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMoTaTL = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        lblMaTL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMainDialog.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainDialog.setRadius(25);
        pnlMainDialog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlExit1.setBackground(new java.awt.Color(253, 127, 127));
        pnlExit1.setRoundBottomLeft(25);
        pnlExit1.setRoundTopRight(25);
        pnlExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlExit1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlExit1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlExit1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlExit1MousePressed(evt);
            }
        });
        pnlExit1.setLayout(new java.awt.GridBagLayout());

        lblExit1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lblExit1.setForeground(new java.awt.Color(255, 255, 255));
        lblExit1.setText("X");
        lblExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExit1MouseClicked(evt);
            }
        });
        pnlExit1.add(lblExit1, new java.awt.GridBagConstraints());

        pnlMainDialog.add(pnlExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 50));

        txtMaTheLoai.setBackground(new java.awt.Color(222, 247, 227));
        txtMaTheLoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaTheLoaiKeyPressed(evt);
            }
        });
        pnlMainDialog.add(txtMaTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 200, 40));

        lblMoTaTL.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMoTaTL.setText("Mô Tả");
        pnlMainDialog.add(lblMoTaTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        txtTenTheLoai.setBackground(new java.awt.Color(222, 247, 227));
        txtTenTheLoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTenTheLoaiKeyPressed(evt);
            }
        });
        pnlMainDialog.add(txtTenTheLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 200, 40));

        lblTenTL.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblTenTL.setText("Tên Thể Loại");
        pnlMainDialog.add(lblTenTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        btnLuuTL.setBackground(new java.awt.Color(87, 190, 110));
        btnLuuTL.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuTL.setText("Lưu Thông Tin");
        btnLuuTL.setBoderColor(new java.awt.Color(87, 190, 110));
        btnLuuTL.setFont(new java.awt.Font("Inter SemiBold", 0, 14)); // NOI18N
        btnLuuTL.setRadius(10);
        btnLuuTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuTLActionPerformed(evt);
            }
        });
        pnlMainDialog.add(btnLuuTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 270, 50));

        jLabel19.setFont(new java.awt.Font("Inter ExtraBold", 0, 26)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(55, 149, 76));
        jLabel19.setText("Thông Tin Loại Sách");
        pnlMainDialog.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 280, -1));

        txtMoTaTL.setColumns(20);
        txtMoTaTL.setRows(5);
        txtMoTaTL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMoTaTLKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtMoTaTL);

        pnlMainDialog.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 670, 210));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ebooks/Image/nerds-removebg-preview.png"))); // NOI18N
        pnlMainDialog.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblMaTL.setFont(new java.awt.Font("Inter Medium", 0, 14)); // NOI18N
        lblMaTL.setText("Mã Thể Loại");
        pnlMainDialog.add(lblMaTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        getContentPane().add(pnlMainDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlExit1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseExited

    private void pnlExit1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlExit1MouseEntered

    private void pnlExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MouseClicked
        // TODO add your handling code here:
     //   System.exit(0);
    }//GEN-LAST:event_pnlExit1MouseClicked

    private void lblExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExit1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblExit1MouseClicked

    private void btnLuuTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuTLActionPerformed
           LuuThongTin();
    }//GEN-LAST:event_btnLuuTLActionPerformed

    private void pnlExit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlExit1MousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_pnlExit1MousePressed

    private void txtMaTheLoaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaTheLoaiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LuuThongTin();
        }
    }//GEN-LAST:event_txtMaTheLoaiKeyPressed

    private void txtTenTheLoaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenTheLoaiKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LuuThongTin();
        }
    }//GEN-LAST:event_txtTenTheLoaiKeyPressed

    private void txtMoTaTLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoTaTLKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LuuThongTin();
        }
    }//GEN-LAST:event_txtMoTaTLKeyPressed

    /*tbdSetting args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TypeBooksDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TypeBooksDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TypeBooksDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TypeBooksDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TypeBooksDiaLog dialog = new TypeBooksDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ebooks.Compoment.MyButton btnLuuTL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExit1;
    private javax.swing.JLabel lblMaTL;
    private javax.swing.JLabel lblMoTaTL;
    private javax.swing.JLabel lblTenTL;
    private com.ebooks.Compoment.PanelRound pnlExit1;
    private com.ebooks.Compoment.PanelRadius pnlMainDialog;
    private javax.swing.JTextField txtMaTheLoai;
    private javax.swing.JTextArea txtMoTaTL;
    private javax.swing.JTextField txtTenTheLoai;
    // End of variables declaration//GEN-END:variables
}
